upstream go_backend {
    server 127.0.0.1:8081;
    keepalive 32;
}

upstream nodejs_backend {
    server 127.0.0.1:3000;
    keepalive 32;
}

server {
	listen 80;
	server_name {{DOMAIN_NAME}};

	location = /sw.js {
		alias {{CLIENT_ROOT}}/sw.js;
		default_type application/javascript;
		add_header Cache-Control "no-cache";
	}

	location /static/ {
		alias {{SERVER_ROOT}}/public/static/;
		expires 30d;
		add_header Cache-Control "public, no-transform";
	}

	location /imgs/ {
		alias {{SERVER_ROOT}}/public/imgs/;
		expires 30d;
		add_header Cache-Control "public, no-transform";
	}

	# костыль для совместимости - не трогать
	location = /join.php {
		try_files $uri $uri/ /join.php?$args;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_param SCRIPT_FILENAME {{SERVER_ROOT}}/public/join.php;
		include fastcgi_params;
	}

	# FIXME: сделать строгое разделение у php/go бекенда
	# php => server/133, go => server/g133
	location /server/ {
		proxy_pass http://go_backend;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	# nodejs реализация, удалить когда golang часть будет готова
	location ~ ^/api(/.*)?$ {
		proxy_pass http://nodejs_backend$1$is_args$args;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	# Реализация загрузчика.
	# ЗАГРУЗЧИК - SSR. Не смейте ставить тут try_files index.html иначе у вас умрёт /loader
	location / {
		proxy_pass http://nodejs_backend$is_args$args;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
	location = /loader {
		proxy_pass http://nodejs_backend$is_args$args;
		proxy_http_version 1.1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	# Архитектурно для версий используется внешний репозиторий
	# собственно я его тут и проксирую
	location /cli/ {
		alias {{CLIENT_ROOT}}/;
		expires 30d;
		add_header Cache-Control "public, no-transform";
	}
}
